### ISSUE TITLE
How to pickle a SyclQueue object?

### ISSUE THREAD

**Issue by chudur-budur** [IntelPython/dpctl#1206]
I was trying to `pickle` a `SyclQueue` object:

```python
import sys
import pickle
import dpctl

print("python: ", sys.version)
print("pickle:", pickle.format_version)
print("dpctl:", dpctl.__version__)

q = dpctl.SyclQueue()

d = pickle.dumps(q)
```

I get this error:

```bash
python:  3.9.16 (main, Jan 11 2023, 16:05:54)
[GCC 11.2.0]
pickle: 4.0
dpctl: 0.14.3dev0+68.g09acd2025
Traceback (most recent call last):
  File "/localdisk/work/$USER/numba-dpex/my-driver.py", line 17, in <module>
    d = pickle.dumps(q)
  File "stringsource", line 2, in dpctl._sycl_queue.SyclQueue.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

How do I `pickle` a `SyclQueue` object?

**Comment by oleksandr-pavlyk** [comment]
The `SyclQueue` object is not pickleable. How would you serialize the object so that you can reconstruct a queue targeting the same device and the same context?  This is conceivably possibly, at present, for root devices and default platform contexts. Even then, saved pickle may not be reconstructable (what if the host machine does not support this device?)

**Comment by oleksandr-pavlyk** [comment]
@chudur-budur Feel free to close this issue if the question has been answered.
