### ISSUE TITLE
Arrays sequence in advanced indexing separated by basic slicing

### ISSUE THREAD

**Issue by antonwolfy** [IntelPython/dpctl#1912]
It seems dpctl supports the arrays sequence in advanced indexing only when it isn't separated by a basic slice:
```python
import numpy, dpctl, dpctl.tensor as dpt

dpctl.__version__
# Out: '0.19.0dev0+280.g4a94ef9c25'

numpy.__version__
# Out: '2.1.3'

a = dpt.ones((4, 4, 4))
a[(dpt.asarray([3, 2]), slice(None), dpt.asarray([1, 0]))].shape
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 a[(dpt.asarray([3, 2]), slice(None), dpt.asarray([1, 0]))].shape

File dpctl/tensor/_usmarray.pyx:924, in dpctl.tensor._usmarray.usm_ndarray.__getitem__()

File dpctl/tensor/_slicing.pxi:192, in dpctl.tensor._usmarray._basic_slice_meta()

IndexError: Advanced indexing array specs may not be separated by basic slicing specs.

# while NumPy seems to have a support of the use case:
na = dpt.asnumpy(a)
na[(numpy.asarray([1, 0]), slice(None), numpy.asarray([3, 2]))].shape
# Out: (2, 4)
```
Is that limitation intentional for dpctl's implementation of advanced indexing?

**Comment by antonwolfy** [comment]
The same error will raise if to use an integer instead of slice:
```python
a[(dpt.asarray([1, 0]), 1, dpt.asarray([3, 2]))].shape
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[9], line 1
----> 1 a[(dpt.asarray([1, 0]), 1, dpt.asarray([3, 2]))].shape

File dpctl/tensor/_usmarray.pyx:924, in dpctl.tensor._usmarray.usm_ndarray.__getitem__()

File dpctl/tensor/_slicing.pxi:192, in dpctl.tensor._usmarray._basic_slice_meta()

IndexError: Advanced indexing array specs may not be separated by basic slicing specs.

# no issue in NumPy
na[(numpy.asarray([1, 0]), 1, numpy.asarray([3, 2]))].shape
# Out: (2,)
```

**Comment by antonwolfy** [comment]
Two more examples below to share deviations against NumPy behavior in indexing of zero-dim and zero-sized arrays (but might be expected):
```python
a = dpt.ones(())  # zero-dim
a[(False, True, True)].shape
# Out: (0, 1, 1)

na = dpt.asnumpy(a)
na[(False, True, True)].shape
# Out: (0,)

a = dpt.ones((0,))  # zero-sized
a[(False, True, True)].shape
# Out: (0, 1, 1, 0)

na = dpt.asnumpy(a)
na[(False, True, True)].shape
# Out: (0, 0)
```

**Comment by oleksandr-pavlyk** [comment]
This is intentional and the current behavior is considered an improvement over NumPy. 

To explain the rationale, let's restrict ourselves to getitem with 1d integral indexing for now. When integral array is used in a single slot, the resulting array has the same number of indexes, but the extent of the array along the axis where integral indexing was used is determined by the size of the index array. For example, 

```python
import dpctl.tensor as dpt
x = dpt.ones((2,3,5))
ii = dpt.asarray([0,3, 4])
assert x[:, :, ii].shape == x.shape[:2] + ii.shape
``` 

When multiple consecutive slots are indexed by integral 1D arrays, these must have the same shape, and the resulting array has  fewer number of dimensions. The consecutive axis along which integral indexing was applied are replaced with a single axis, along extracted array values are placed. The location of this single axis is unambiguous (it is replaces the sequence of integral arrays):

```python
import dpctl.tensor as dpt
x = dpt.ones((2,5,6,7))
ii1 = dpt.asarray([0, 2, 4])
ii2 = dpt.asarray([1, 3, 5])
assert x[:, ii1, ii2, :].shape == (2, 3, 7)
``` 

```python
import dpctl.tensor as dpt
x = dpt.ones((5,6,4,2))
ii1 = dpt.asarray([0, 2, 4])
ii2 = dpt.asarray([1, 3, 5])
ii3 = dpt.asarray([0, 2, 1])
assert x[ii1, ii2, ii3, :].shape == (3, 2)
```

When the basic indexing slice separates advanced indexing integral arrays, the location of the new axis which corresponds to zipping through indexes of integral arrays can not be unambiguously determined.

```python
import dpctl.tensor as dpt
x = dpt.ones((6, 3, 4, 5))
# Should x[:, dpt.asarray([2, 1, 0]), :, dpt.array([4, 3, 2])]  have shape (6, 3, 4), or (6, 4, 3), or (3, 6, 4)?
```

NumPy chooses to resolve this ambiguity by always placing the new axis as the zero axis, so for NumPy the following is true:

```python
import numpy as np
a = np.ones((6, 3, 4, 5))
assert a[:, np.asarray([2,1,0]), :, np.asarray([4,3,2])].shape == (3, 6, 4)
```

But this is not always intuitive, or useful, and hence causes an exception to be raised to encourage user to be explicit. 

Array API leaves advanced indexing with use of multiple integral array unspecified at the moment.

**Comment by antonwolfy** [comment]
Thank you @oleksandr-pavlyk for detailed explanation. Now the behavior and intentions are crystal clear.
