### ISSUE TITLE
Implement IPC

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/dpctl#258]
An instance of IpcHandle is required to be returned from an implementation of get_ipc_handle()

**Comment by oleksandr-pavlyk** [comment]
I suppose this ticket refers to [Intel-Process-Communication](https://spec.oneapi.io/level-zero/latest/core/PROG.html#inter-process-communication) support in Level-zero driver.

@diptorupd The question is whether dpctl should provide API to call level-zero. If Numba needs this, they can call functions from `ze_loader` directly, since it is a C library.

**Comment by diptorupd** [comment]
> @diptorupd The question is whether dpctl should provide API to call level-zero. If Numba needs this, they can call functions from `ze_loader` directly, since it is a C library.

Agreed. I am closing the issue as unrelated to dpctl.
