### ISSUE TITLE
`dpctl.tensor` ignores active `dpctl.device_context`

### ISSUE THREAD

**Issue by fcharras** [IntelPython/dpctl#887]
The following snippet:

```python
import dpnp
import dpctl
with dpctl.device_context("cpu"):
    array = dpctl.tensor.empty(sh=(3,3))
    print(array.device)
```

displays `Device(opencl:gpu:0)` where `Device(opencl:cpu:0)` would be expected.

Currently, the expected result requires to explicitly pass the current queue:

```python
import dpnp
import dpctl
with dpctl.device_context("cpu"):
    array = dpctl.tensor.empty(sh=(3,3), device=dpctl.get_current_queue())
    print(array.device)
```

This behavior is seen with all tensor creation functions.

**Comment by oleksandr-pavlyk** [comment]
This is by design. Array API advocates for local control for data allocation target (see [array API's design considerations](https://data-apis.org/array-api/latest/design_topics/device_support.html#design-topics-device-support--page-root) for rationale).

The default behavior is to allocate data on default-selected device and bind it to an associated queue.

**Comment by fcharras** [comment]
Thank you for the rationale, [the `dpctl.tensor` documentation](https://intelpython.github.io/dpctl/latest/docfiles/dpctl/dpctl.tensor_pyapi.html?#module-dpctl.tensor) is actually also explicit about it and I can get behind that, let's just close the issue.
